# Generated by Django 3.1.5 on 2021-03-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('song_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.song')),
                ('author_name', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
            ],
            bases=('core.song',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('song_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.song')),
                ('host', models.CharField(max_length=100)),
            ],
            bases=('core.song',),
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participants', to='core.podcast')),
            ],
        ),
    ]
